### ISSUE TITLE
Manual assigned IP not showed up

### ISSUE THREAD

**Issue by AdziePahlevi** [VREMSoftwareDevelopment/bwmon#21]
Hello Expert, 

thanks a lot for creating this mods for AsusWRT Merlin, it is really help by the way. however I was discovering for the devices that have IP that manually assigned is not coming in the list.  below is the snapshow

from router client list
![image](https://user-images.githubusercontent.com/19539988/156635401-62366aee-b85a-45d5-b09e-a90ebcf628c1.png)

from bwmon page
![image](https://user-images.githubusercontent.com/19539988/156635518-f039413d-9e20-44c0-a80a-375d0e9bb930.png)

any idea how to force refresh or put all user IP address regardless assigned by DHCP or manual assignment?

thank you for the advice

BR// Ajie

**Comment by VREMSoftwareDevelopment** [comment]
Application uses cron to execute data collection script

**Code references:**
https://github.com/VREMSoftwareDevelopment/bwmon/blob/master/server
https://github.com/VREMSoftwareDevelopment/bwmon/blob/master/server/S80bwmon
https://github.com/VREMSoftwareDevelopment/bwmon/blob/master/server/S80bwmon#L37
