### ISSUE TITLE
Documentation for setting up User names

### ISSUE THREAD

**Issue by maphew** [VREMSoftwareDevelopment/bwmon#3]
I created a stub for documenting the `macnames` file, https://github.com/maphew/bwmon/commit/473f63af18dc9dc5ce7ef4fb8f4618bc7ddfe070

however I know I'm missing critical stuff, like how to get it take effect.;-) 
(Editing the file on my machine does not change the user names in the web page)

Also wording should probably be changed to Computer or Device name through out application as it's not really user names. It won't capture multiple users on one device as separate people for example.

I tried looking at the demo for inspiration, https://github.com/VREMSoftwareDevelopment/bwmon/tree/gh-pages/demo, but the data files aren't included. (so how does the demo even work?)

**Comment by VREMSoftwareDevelopment** [comment]
1. Good point, user vs device. 
2. The macnames file is generated from Router Static IP Table and WiFi Filter setup.
3. Demo uses pre-generated data file 'bwmonUsage.js'. 

Can you tell which router model you are using?

**Comment by maphew** [comment]
re 2: oh, that means it shouldn't be user-edited then. I thought it was for adding names to devices where hostname lookup doesn't work (or is ugly, like android3248956294).

Router is [Asus RT-N12 D1](https://www.asus.com/ca-en/Networking/RTN12_D1/)

**Comment by VREMSoftwareDevelopment** [comment]
There is always a possibility to enhanced the script to use an additional custom 'macnames' files.
