### ISSUE TITLE
3.1.1 install seems to only show the demo data

### ISSUE THREAD

**Issue by bhomrich** [VREMSoftwareDevelopment/bwmon#32]
I installed the 3.1.1 release today using the instructions on the README.md,   and while I can see updates running every 30 minutes like the cron setup is configured,  the UI shows ONLY the demo data.

Where is the react UI configured to read the database file?    I don't see any obvious place where the db location is specified,  and my guess is it's not accurate for the way my install is configured.

Thx

**Comment by VREMSoftwareDevelopment** [comment]
After installation:
- Data collector can be found in the  `/opt/share/bwmon/` 
- React UI can be found in the `/opt/share/www/bwmon`
- Data collector automatically updates the data file `usage.db` in the `/opt/share/www/bwmon` using cron
- React UI uses the data file `usage.db`

References:
- [Scripts folder](https://github.com/VREMSoftwareDevelopment/bwmon/tree/master/server)
- [Installation script](https://github.com/VREMSoftwareDevelopment/bwmon/blob/master/server/install.sh)
- [Data collection script](https://github.com/VREMSoftwareDevelopment/bwmon/blob/master/server/bwmon.sh)

**Comment by bhomrich** [comment]
I can see that the cron job is running to grab recent activity 
I can also see the usage.db being updated in /opt/share/www/bwmon:    I see ONLY my host data in that file for January....

However,  despite that file being available and updated in the last few minutes,   it doesn't appear to be used at all.   
I have gone so far as to move the file to a new name,  and restart my router.   the UI doesn't complain at all when it redraws. (I didn't see any error anywhere when the file was missing.)

I enabled dev tools in the browser,  and put some breaks into the Usage.js for the API to retrieve the file.   Every response I was given had 251 rows (the same number as the public/usage.db in your repo. ),   never the 8 in my external usage.db.

I don't quite follow how a react build working,  it's acting like the response is never being returned as anything but a constant.   (BTW,  it's marked that way in the Usage class source code in your repo.)

I'll keep looking (and setup a dev environment to learn a little React....),  but any insight into what might be going on would be helpful.

**Comment by VREMSoftwareDevelopment** [comment]
Looks like collector is working and updating usage data correctly.

Please check the following:
- Is `entware` or `optware` and `lighttpd` installed?
- Is `lighttpd` configured correctly?
- Is `lighttpd` port configured correctly (can not use port 80 - router is using port 80 already)?

What do you see when you try the following: `http://<your_router_ip>:<lighttpd_port>/bwmon/index.html`?

The above instructions are displayed and are in [installation script](https://github.com/VREMSoftwareDevelopment/bwmon/blob/master/server/install.sh)

**Comment by bhomrich** [comment]
I have entware and lighttpd installed and running.    the httpd is running on port81 as you can see from the screen shot

![bwmon](https://github.com/VREMSoftwareDevelopment/bwmon/assets/11426885/8d3e60d4-40eb-4867-9682-87ab3fba230e)

**Comment by VREMSoftwareDevelopment** [comment]
Try the [browser hard reload page](https://www.contractsafe.com/support/how-to-clear-your-browser-cache-and-hard-refresh).

If the above does not work: 
1.  restart lighttpd
1. browser hard reload page 

Hopefully these will help
Really very strange issue

**Comment by VREMSoftwareDevelopment** [comment]
@bhomrich Did any of suggestion worked?
