### ISSUE TITLE
"cru: not found" during installation

### ISSUE THREAD

**Issue by karimnouh** [VREMSoftwareDevelopment/bwmon#4]
Problem with cru while installing on DD-WRT.

> root@DD-WRT:/jffs/bwmon1/bwmon-master/server# ./bwmon-cron.sh install
> ./bwmon-cron.sh: line 37: cru: not found
> ./bwmon-cron.sh: line 37: cru: not found
> ln: /tmp/var/wwwext/bwmon: No such file or directory

Any suggestions would be appreciated.

**Comment by VREMSoftwareDevelopment** [comment]
cru is a Cron Utility. 
Please make sure it is installed on your router and in the path.
