### ISSUE TITLE
cru: not found

### ISSUE THREAD

**Issue by akacross** [VREMSoftwareDevelopment/bwmon#5]
i'm using openwrt 15.05.1

it has crontab but no cru. i don't quite understand this lol.

**Comment by VREMSoftwareDevelopment** [comment]
Please take a look at Issue #4

**Comment by akacross** [comment]
yeah I've researched Cron Utility, i really can't find nothing but crontabs from openwrt wiki.

**Comment by VREMSoftwareDevelopment** [comment]
**bwmon-cron.sh** is shell script to install or remove bandwidth usage monitor from cron jobs using **cru** utility. Since **cru** utility is not available or not provided on the router, by customizing the **bwmon-cron.sh** script or manually adding the cron jobs to **crontab** should solve the problem.  We do encourage users/developers to fork the project and become contributors.

**Comment by akacross** [comment]
i have got this far but its not showing anything in the page.
`echo "* * * * * $BWMON setup $BWDIR" >> bwmon_setup
	crontab bwmon_setup
	echo "0,30 * * * * $BWMON update $BWDIR" >> bwmon_update
	crontab bwmon_update

and it created 2 files in the bwmon directory instead of in /etc/contabs

i also changed`BWMONWWW=/www/bwmon

so it can be accessed at 192.168.1.1/bwmon

**Comment by akacross** [comment]
after looking into this further, i'm not exactly sure if this will even work because OpenWRT 15.05.1 uses UCI and not NVRAM.

**Comment by VREMSoftwareDevelopment** [comment]
To switch to UCI will require more changes to main script.
Did you try [https://github.com/vortex-5/ddwrt-bwmon](https://github.com/vortex-5/ddwrt-bwmon)?
Can you tell which router model you are using?

**Comment by akacross** [comment]
I was actually running OpenWRT 15.05.1 in a VM, with windows 7 on an internal network shared between the Openwrt VM and win7 vm so i can SHH, and edit files etc.. but my router is a WNDR3700v1 running OpenWRT 15.05.1

also that bwmon by Vortex-5, it has a issue not quite sure what it is, but i edit it with the changes from this guy https://github.com/vortex-5/ddwrt-bwmon/issues/29 and it seems like my DHCP Leases break on reboot and the only way for them to show up either for the leases to renew on there own or reset both my computer and server.

if you want to try and get this working on OpenWRT i would gladly show you how to get it running on VitrualBox or even let you Teamviewer my VM lol.
