### ISSUE TITLE
How do you install this? I followed all the directions when I reached the

### ISSUE THREAD

**Issue by rayray668** [VREMSoftwareDevelopment/bwmon#6]
I followed all the directions when I reached the
./bwmon-cron.sh install I ran the command and it now says

./bwmon-cron.sh: line 37: cru: not found
./bwmon-cron.sh: line 37: cru: not found
ln: /tmp/var/wwwext/bwmon: No such file or directory

and it will not install

**Comment by VREMSoftwareDevelopment** [comment]
Duplicate #5
